#!/usr/bin/env python

import sys
import argparse
import os
from pynux import utils
from pprint import pprint as pp


def main(argv=None):

    parser = argparse.ArgumentParser(description='nuxeo metadata via REST API')
    parser.add_argument('path', nargs=1, help="nuxeo document path")
    parser.add_argument('--outdir')
    if argv is None:
        argv = parser.parse_args()

    nx = utils.Nuxeo()
    documents = nx.children(argv.path[0])

    if argv.outdir:
        outdir = os.path.abspath(os.path.expanduser(argv.outdir)) # Expand user- and relative-paths
        nx.copy_metadata_to_local(documents, outdir)
    else:
        nx.print_document_summary(documents)


# main() idiom for importing into REPL for debugging
if __name__ == "__main__":
    sys.exit(main())
