#!/usr/bin/env python

import sys
import argparse
from pynux import utils


def main(argv=None):
    parser = argparse.ArgumentParser(description='nuxeo metadata via REST API')
    if argv is None:
        argv = parser.parse_args()

    # http://demo.nuxeo.com/nuxeo/api/v1/path/default-domain/@search\?query\=SELECT%20\*%20FROM%20Document\&pageSize\=2\&currentPageIndex\=1 | jq .
    # todo; add these defaults as parameters as well as env
    nx = utils.Nuxeo()
    documents = nx.all()
    nx.print_document_summary(documents)


# main() idiom for importing into REPL for debugging
if __name__ == "__main__":
    sys.exit(main())
