#!/usr/bin/env python

import sys
import argparse
import os
from pynux import utils
from pprint import pprint as pp


def main(argv=None):

    parser = argparse.ArgumentParser(description='nuxeo platform importer log/logActivate')
    parser.add_argument('--activate', action='store_true')
    if argv is None:
        argv = parser.parse_args()

    nx = utils.Nuxeo()

    if argv.activate:
        nx.import_log_activate()
    else:
        nx.import_log()


# main() idiom for importing into REPL for debugging
if __name__ == "__main__":
    sys.exit(main())
